[project]
name = "legoagent"
version = "0.1.0"
description = "Lego Mindstorms meets LLMs"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=1.63.0",
    "python-dotenv>=1.0.1",
    "python-ev3dev2>=2.1.0.post1",
]
